package smart_home.reports;

/**
 * Class Report supplies functions to create various reports about simulation.
 */
public class Report {
    
    /**
     * Method generateHouseConfigurationReport generates report containing data about current state of the house and its content.
     */
    public void generateHouseConfigurationReport() {
        
    }
    
    /**
     * Method generateEventReport generates report containing the history of events that happened.
     */
    public void generateEventReport() {
        
    }
    
    /**
     * Method generateActivityAndUsageReport generates report containing actions of people and animals.
     */
    public void generateActivityAndUsageReport() {
        
    }
    
    /**
     * Method generateConsumptionReport generates report containing data of devices' consumptions.
     */
    public void generateConsumptionReport() {
        
    }
    
    /**
     * Method generateAllReports generates all of the reports generated by this class.
     */
    public void generateAllReports() {
        generateHouseConfigurationReport();
        generateEventReport();
        generateActivityAndUsageReport();
        generateConsumptionReport();
    }
    
}
